### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by electerious** [electerious/Ackee#129]
This is the first major backend and frontend rewrite of Ackee. I've tried to add a Dashboard to Ackee that shows multiple statistics at a glance. Turns out this is hardly possible with the current API as the dashboard requires data from different endpoints. I've therefore decided to switch to GraphQL, making it easier to aggregate the data needed for the current view. The API is now self-documented, returns better results and allows me to delete a bunch of code.

You can simple update to the new version by pulling the newest code, but I don't recommend to do so until it's ready.

I've started working on v2 in the beginning of May and I guess that it will take till the end of August until it's done. It's a lot of work and I'm more than happy for every kind of support: https://github.com/sponsors/electerious

Here's what has already been added: https://github.com/electerious/Ackee/blob/develop/CHANGELOG.md

I will keep the task-list up-to-date while working on it.

### Backend tasks for Ackee

- [x] GraphiQL should only be available when enabled
- [x] Update "Fill database" script to use the new API
- [x] Check if all files are still in use. There might me some files no longer necessary.

### Frontend tasks for Ackee

- [x] Use new GraphQL API (_WIP_)
- [x] Scroll to top when switching pages
- [x] Write API examples and documentation
- [x] Check if all files are still in use. There might me some files no longer necessary.
- [x] Options to customise the dashboard and what the cards are showing => We use unique, daily and top data for now
- [x] Prevent context menus in filter and navigation to leave the screen on small screens
- [x] Overview doesn't show up in the errors or fetching prop because it uses a symbol

### Tasks for ackee-tracker

- [x] Use new GraphQL API

### Testing

- [x] Test if all endpoints are protected with a authentication
- [x] Test that protected operations aren't possible in the demo mode
- [x] Ensure that tokens are invalid after the TTL
- [ ] Test CORS options with new API
- [x] Run Ackee with an empty installation
- [x] Run Ackee with an existing installation
- [x] Test all features
- [x] Check if all files are still in use. There might me some files no longer necessary.
- [x] Cross browser testing
- [x] Ensure that GraphQL errors don't contain sensitive data

### Tasks for Ackee 2.x

- [ ] Write tests for new API and files
- [ ] Check why the recent aggregation is so slow
- [ ] Views and durations are almost identical when it comes to the aggregation and enhancers. The code should be combined.
- [ ] Improve performance of facts / GraphQL resolvers
- [x] Don't fetch data for each domain / Fetch data for all domains / e.g. `props.fetchBrowsers(props, domain.id)` 
- [x] Implement DataLoader to avoid too many `domains.all()` calls

**Comment by electerious** [comment]
The first version has been successfully deployed on my server. It's now possible to test Ackee v2:

```
docker pull electerious/ackee:develop
```

Make sure to backup your data. There's also new version of `ackee-tracker` (4.0.0-1) in case you aren't using the version served by the Ackee installation.

**Comment by electerious** [comment]
Here we go 🚀 https://github.com/electerious/Ackee/releases/tag/v2.0.0

**Comment by HyperTesto** [comment]
Docker compose + traefik works perfectly. 2 minutes update :100:
